# Generated by Django 5.2.4 on 2025-08-03 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Укожите Отделение')),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Укожите специальность')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30)),
                ('firs_name', models.CharField(max_length=40)),
                ('birthday', models.DateField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flay.department')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flay.specialization')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30)),
                ('class_hospital', models.CharField(max_length=50)),
                ('address', models.TextField(db_index=True)),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='Время открытия')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='Время закрытия')),
                ('date', models.DateField()),
                ('doctors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flay.doctor')),
            ],
            options={
                'verbose_name': 'Госпиталь',
                'verbose_name_plural': 'Госпитали',
            },
        ),
    ]
