# Generated by Django 5.2.4 on 2025-08-16 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Укожите Отделение')),
            ],
            options={
                'verbose_name': 'Департамент',
                'verbose_name_plural': 'Департаменты',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Укожите специальность')),
                ('descriptions', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Спецалсит',
                'verbose_name_plural': 'Спецалситы',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30)),
                ('firs_name', models.CharField(max_length=40)),
                ('birthday', models.DateField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flay.department')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flay.specialization')),
            ],
            options={
                'verbose_name': 'Доктор',
                'verbose_name_plural': 'Доктора',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30)),
                ('class_hospital', models.CharField(max_length=50)),
                ('address', models.TextField(db_index=True)),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='Время открытия')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='Время закрытия')),
                ('date_create', models.DateField()),
                ('doctors', models.ManyToManyField(to='flay.doctor')),
            ],
            options={
                'verbose_name': 'Госпиталь',
                'verbose_name_plural': 'Госпитали',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30)),
                ('firs_name', models.CharField(max_length=40)),
                ('birthday', models.DateField()),
                ('attending_physician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flay.doctor')),
                ('the_hospital', models.ManyToManyField(to='flay.hospital')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flay.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='flay.patient')),
            ],
            options={
                'verbose_name': 'Диагназ',
                'verbose_name_plural': 'Диагназы',
            },
        ),
    ]
