# Generated by Django 5.2.4 on 2025-08-03 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flay', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Департамент', 'verbose_name_plural': 'Департаменты'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Доктор', 'verbose_name_plural': 'Доктора'},
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'verbose_name': 'Спецалсит', 'verbose_name_plural': 'Спецалситы'},
        ),
    ]
