# Generated by Django 5.2.4 on 2025-08-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flay', '0002_alter_department_options_alter_doctor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='descriptions',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
