# Generated by Django 5.2.4 on 2025-08-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flay', '0003_specialization_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='descriptions',
            field=models.TextField(blank=True),
        ),
    ]
