# Generated by Django 5.2.4 on 2025-08-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flay', '0004_alter_specialization_descriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='doctors',
        ),
        migrations.AddField(
            model_name='hospital',
            name='doctors',
            field=models.ManyToManyField(to='flay.doctor'),
        ),
    ]
